name: Generate Snake (Windows Only, No Docker)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: (Optional) Download pre-generated snake assets
        run: |
          echo "Simulating asset preparation..."
          mkdir dist
          curl -L -o dist/snake.svg https://example.com/your-prebuilt-snake.svg

      - name: Show build status
        run: git status

      - name: Push files to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: Update snake animations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

